"use client";
import "./globals.css";
import type { AppProps } from "next/app";
import { RecoilRoot } from "recoil";
import authOptions  from "../app/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { SessionProvider } from 'next-auth/react'
import Signin from "./signin/page";
import Home from "./page";

// type Props = {
//   children: JSX.Element;
// };

// const Auth = ({children}: Props): JSX.Element => {
//   const isLoading = useAuth();
//   return isLoading ? <p>Loading...</p> : children;
// };

// export const metadata: Metadata = {
//   title: "Next.js Todo List",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="ja">
      <body>
        <SessionProvider session={session}>
          <RecoilRoot>
            <header>Next.js Todo List 後で調整</header>
            {children}
          </RecoilRoot>
        </SessionProvider>
      </body>
    </html>
  );
}
