import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header>Next.js Todo List 後で調整</header>
        <div className="w-5/6 mx-auto">{children}</div>
      </body>
    </html>
  );
}
