"use client";
import type { AppProps } from "next/app";
import { RecoilRoot } from "recoil";
import { useAuth } from "./firebase/auth";

// import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "../provider/SessionProvider"

type Props = {
  children: JSX.Element;
};

const Auth = ({children}: Props): JSX.Element => {
  const isLoading = useAuth();
  return isLoading ? <p>Loading...</p> : children;
};


// export const metadata: Metadata = {
//   title: "Next.js Todo List",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
    <html lang="ja">
      <body>
        <RecoilRoot>          
        <header>Next.js Todo List 後で調整</header>
        <Auth>
        <div className="w-5/6 mx-auto">{children}</div>
        </Auth>
        </RecoilRoot>
      </body>
    </html>
    </SessionProvider>
  );
}
